### ISSUE TITLE
Roadmap for 3.0

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ThomasBleijendaal/RapidCMS#17]
For the 3.0 version of RapidCMS the following features and changes must be made:

- [x] Decouple the Config to Setting conversion and abstract the config section away with a IConfigProvider of some sorts to allow for dynamic config (to allow for generating config automatically based on convention and [Display] and such, and allow for generating workflow types of UI based on dynamic config and custom decision making classes).

- [x] Create an IConfigProvider system for the current way of configuring RapidCMS.

- [x] Create an IConfigProvider system for a new convention based way of configuring RapidCMS (#16).

- [x] Create an IConfigProvider system for a new workflow style of interaction withing RapidCMS (wizard-like style interaction for a more guided / decision based CMS). --> #20 

- [x] Decouple the server-side stuff from the Razor components within RapidCMS to allow for running RapidCMS client-side which will talk to an API behind an IRepository. Have the RapidCMS.ServerSide and RapidCMS.WebAssembly both depend on a common Razor components library, so choosing either deployment mode should be easily interchangeable. 

- [x] Create a bridging IRepository to allow a working client-side CMS talking to an BaseRepositoryController derived controller on the backend (either rest, websocket, grpc, what works best for the scenario). 

- [x] Support all repository features in Apis that are currently supported in ServerSide and WebAssembly.

- [x] Add support for simple localization (especially for convention based configurations). #21

- [x] ~~Open up some of the shielded config and setup classes to allow for better custom convention builders to be created.~~

- [x] Improve front-end CSS.

- [x] Implement API-side DataViewResolver.

- [x] Add `.ConfigureAwait(false)` where applicable.

- [x] Add MappedApiRepository.

- [x] Update documentation + make demo site for WebAssembly CMS.

- [x] Inline defined collections do not work correctly with ApiRepository (their alias are guids, so no HttpClient is defined for that). #22
